In [29]:
import pandas as pd 
import numpy as np
from matplotlib import pyplot as plt

def limit(x,min,max):
    if(x<min):
        return min
    if(x>max):
        return max
    return x

df_true=pd.DataFrame(columns=['s','b','t'])
student_count=100
minmarks=0
maxmarks=100
no_of_grades=10
mu_true=60
sigma_true=15
beta_true=10  #beta is actually 10. so when we use 1/beta , we are using 0.1 instead

#generate true values
for u in range(0,student_count):   
    #s_u true scores for each grader 
    su=np.random.normal(mu_true,sigma_true,1)[0]
    su=limit(su,minmarks,maxmarks)
        
    #bias of each user ranges from 0-
    bu=np.random.normal(0,no_of_grades,1)[0]
    bu=limit(bu,-no_of_grades,no_of_grades)
    
    #t -> reliability
    tu=np.random.normal(su,beta_true,1)[0]
    df_true.loc[u]=[su,bu,tu]


df_true

             s          b           t
0    47.662032   0.620922   41.199980
1    61.212017  -2.364678   75.429932
2    80.508754   9.272958   70.783527
3    64.815991   5.590940   56.225314
4    56.176985  -1.776667   66.028286
5    40.343677  -5.290653   40.850778
6    65.005353   9.425062   64.907074
7    69.841907  -4.440422   96.611347
8    52.683965  10.000000   45.250848
9    63.396468   0.209255   70.006231
10   49.178448  -4.719910   46.084188
11   84.441752   0.860232   90.631153
12   61.909136   5.331673   71.369571
13   75.674749  10.000000   67.270159
14   48.010769   6.541129   53.103054
15   48.152644  -4.821070   40.794089
16   55.493086 -10.000000   50.571855
17   75.335017   2.246997   95.818793
18   78.088842  10.000000   75.457228
19   54.875348  -3.471807   52.693968
20   63.166325   3.470054   67.664888
21   56.181808  -6.550409   41.602755
22   57.885537  10.000000   60.807702
23   59.075454  -6.449164   70.452336
24   48.480533   7.022003   45.519906
25   63.355972  10.000000   62.255700
26  100.000000  -8.292318   81.797713
27   91.362809  10.000000  102.350425
28   56.603199  -7.362037   69.266328
29   84.696267  10.000000   81.387082
..         ...        ...         ...
70   63.431162  -0.567482   66.086424
71   87.609980  -0.654699   91.083308
72   71.710540  10.000000   60.766112
73   45.472295  10.000000   34.777371
74   49.212423   3.879401   38.104656
75   45.868349   6.383406   52.490994
76   71.130341  10.000000   65.151459
77   56.387326   1.395755   66.370474
78   27.704548  10.000000   27.226041
79   30.434912   9.678611   39.562020
80   60.554524   8.039851   74.197214
81   61.158096  10.000000   71.169125
82   59.039415   3.184998   52.738806
83   68.270994   2.700718   84.632193
84   61.023102   1.343648   73.512464
85   55.072807  -0.633207   73.320282
86   59.263068   7.265794   63.938670
87   34.401412   6.417269   35.043009
88   65.123418   0.672475   64.768056
89   23.666469 -10.000000   35.471718
90   49.152387  -3.657209   39.783665
91   59.260006  -2.935280   51.398834
92   63.534016  -7.925041   52.032075
93   58.773447  -1.680404   42.198990
94   66.862465  10.000000   86.730643
95   58.815732   7.789078   63.001317
96   46.346227  -5.666388   49.791851
97   81.316735   2.299231   75.967046
98   40.582421 -10.000000   31.105393
99   49.493444   5.327754   60.704431

[100 rows x 3 columns]

In [13]:
df=pd.DataFrame(columns=['a','b'])
df[len(df)]=[]

In [19]:
df

     a    b  0
0  NaN  NaN  1
1  NaN  NaN  2